    - bash ./deploy.sh
    - rsync -av --delete --exclude=".*" /path/to/source/ /path/to/destination/

---
deployment:
  tasks:
    - export DEPLOYPATH=/home/temporizer/cleantouchllc.net/
    - export REPOPATH=/home/temporizer/repositories/cleantouch/
    - /usr/bin/rsync -avz --exclude='.*' $REPOPATH $DEPLOYPATH
